: CLEAR_THREE
0 = SWAP 0 = AND SWAP 0 = AND ;

: CLEAR_CONER
L LT T CLEAR_THREE R RT T CLEAR_THREE R RB B CLEAR_THREE B LB L CLEAR_THREE OR OR ; 

CREATE EDGES L , LT , T , RT , R , RB , B , LB ,

VARIABLE COUNTER
VARIABLE TEMP_MASSIVE
: FIND_ZERO
TEMP_MASSIVE ! -1 COUNTER !
 BEGIN
  1 COUNTER +!
 COUNTER @ 7 > TEMP_MASSIVE @ COUNTER @ 4 * + @ 0 = OR  UNTIL
 COUNTER @ ;

VARIABLE TEMP1
VARIABLE EDGES2
: BUILD_DIFF 
TEMP1 ! EDGES1 ! 0 COUNTER !
 BEGIN
  EDGES1 COUNTER @ 4 * @ > 0
  EDGES1 COUNTER @ 1 + 8 MOD 4 * @ 0 >
  AND
  EDGES1 COUNTER @ 4 * @ 
  EDGES1 COUNTER @ 1 + 8 MOD 4 * @ =
IF
 0 
ELSE
 1
THEN
TEMP1 COUNTER @ 4 * !
 1 COUNTER +! COUNTER @ 7 > UNTIL

: RES
